### ISSUE TITLE
How do i access the text in textfield?

### ISSUE THREAD

**Issue by kalaichelvan** [SethSky/KOAlertController#2]
I would like to access the text of uitextfield added to the alert controller when user press the action button. When i use 

alertController.alertTextField.text

Application crashed. Any help?

**Comment by SethSky** [comment]
If you not assigned UITextField to `alertTextField`, property `alertTextField`  will equal nil. Property  `alertTextField`  only for use custom UITextField. 
If you need `alertController` with text field and change text in UITextField, use 
`alertController.addTextField { (textField) in
            textField.text = "Change text"
}`
Look exemple project `With UITextField` and `Alert with custom UITextField`.

**Comment by kalaichelvan** [comment]
You are right. That is how we add the uitextfield to the alert controller as also seen in example. After textfield's text is changed, how can i get the updated text property when i click the "OK" button?

**Comment by SethSky** [comment]
Just pass the link out of the closure and use this variable
`var tempTextField : UITextField!`
`alertController.addTextField { (textField) in`
`tempTextField =  textField`
`}`

**Comment by kalaichelvan** [comment]
Awesome. Working great. Thanks for your Assistance
